# Generated by Django 5.2.2 on 2025-06-08 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "announcement_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Announcement ID",
                    ),
                ),
                (
                    "announcement",
                    models.TextField(max_length=1024, verbose_name="Announcement"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CDUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("intermediate", "Intermediate"),
                            ("normal", "Normal"),
                            ("member", "Member"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Afghanistan, AF", "Afghanistan, AF"),
                            ("Albania, AL", "Albania, AL"),
                            ("Algeria, DZ", "Algeria, DZ"),
                            ("American Samoa, AS", "American Samoa, AS"),
                            ("Andorra, AD", "Andorra, AD"),
                            ("Angola, AO", "Angola, AO"),
                            ("Anguilla, AI", "Anguilla, AI"),
                            ("Antarctica, AQ", "Antarctica, AQ"),
                            ("Antigua and Barbuda, AG", "Antigua and Barbuda, AG"),
                            ("Argentina, AR", "Argentina, AR"),
                            ("Armenia, AM", "Armenia, AM"),
                            ("Aruba, AW", "Aruba, AW"),
                            ("Australia, AU", "Australia, AU"),
                            ("Austria, AT", "Austria, AT"),
                            ("Azerbaijan, AZ", "Azerbaijan, AZ"),
                            ("Bahamas, BS", "Bahamas, BS"),
                            ("Bahrain, BH", "Bahrain, BH"),
                            ("Bangladesh, BD", "Bangladesh, BD"),
                            ("Barbados, BB", "Barbados, BB"),
                            ("Belarus, BY", "Belarus, BY"),
                            ("Belgium, BE", "Belgium, BE"),
                            ("Belize, BZ", "Belize, BZ"),
                            ("Benin, BJ", "Benin, BJ"),
                            ("Bermuda, BM", "Bermuda, BM"),
                            ("Bhutan, BT", "Bhutan, BT"),
                            ("Bolivia, BO", "Bolivia, BO"),
                            (
                                "Bonaire, Sint Eustatius and Saba, BQ",
                                "Bonaire, Sint Eustatius and Saba, BQ",
                            ),
                            (
                                "Bosnia and Herzegovina, BA",
                                "Bosnia and Herzegovina, BA",
                            ),
                            ("Botswana, BW", "Botswana, BW"),
                            ("Bouvet Island, BV", "Bouvet Island, BV"),
                            ("Brazil, BR", "Brazil, BR"),
                            (
                                "British Indian Ocean Territory, IO",
                                "British Indian Ocean Territory, IO",
                            ),
                            ("Brunei Darussalam, BN", "Brunei Darussalam, BN"),
                            ("Bulgaria, BG", "Bulgaria, BG"),
                            ("Burkina Faso, BF", "Burkina Faso, BF"),
                            ("Burundi, BI", "Burundi, BI"),
                            ("Cabo Verde, CV", "Cabo Verde, CV"),
                            ("Cambodia, KH", "Cambodia, KH"),
                            ("Cameroon, CM", "Cameroon, CM"),
                            ("Canada, CA", "Canada, CA"),
                            ("Cayman Islands, KY", "Cayman Islands, KY"),
                            (
                                "Central African Republic, CF",
                                "Central African Republic, CF",
                            ),
                            ("Chad, TD", "Chad, TD"),
                            ("Chile, CL", "Chile, CL"),
                            ("China, CN", "China, CN"),
                            ("Christmas Island, CX", "Christmas Island, CX"),
                            ("Cocos Islands, CC", "Cocos Islands, CC"),
                            ("Colombia, CO", "Colombia, CO"),
                            ("Comoros, KM", "Comoros, KM"),
                            ("Congo, CD", "Congo, CD"),
                            ("Congo, CG", "Congo, CG"),
                            ("Cook Islands, CK", "Cook Islands, CK"),
                            ("Costa Rica, CR", "Costa Rica, CR"),
                            ("Croatia, HR", "Croatia, HR"),
                            ("Cuba, CU", "Cuba, CU"),
                            ("Curaçao, CW", "Curaçao, CW"),
                            ("Cyprus, CY", "Cyprus, CY"),
                            ("Czechia, CZ", "Czechia, CZ"),
                            ("Côte d'Ivoire, CI", "Côte d'Ivoire, CI"),
                            ("Denmark, DK", "Denmark, DK"),
                            ("Djibouti, DJ", "Djibouti, DJ"),
                            ("Dominica, DM", "Dominica, DM"),
                            ("Dominican Republic, DO", "Dominican Republic, DO"),
                            ("Ecuador, EC", "Ecuador, EC"),
                            ("Egypt, EG", "Egypt, EG"),
                            ("El Salvador, SV", "El Salvador, SV"),
                            ("Equatorial Guinea, GQ", "Equatorial Guinea, GQ"),
                            ("Eritrea, ER", "Eritrea, ER"),
                            ("Estonia, EE", "Estonia, EE"),
                            ("Eswatini, SZ", "Eswatini, SZ"),
                            ("Ethiopia, ET", "Ethiopia, ET"),
                            (
                                "Falkland Islands [Malvinas], FK",
                                "Falkland Islands [Malvinas], FK",
                            ),
                            ("Faroe Islands, FO", "Faroe Islands, FO"),
                            ("Fiji, FJ", "Fiji, FJ"),
                            ("Finland, FI", "Finland, FI"),
                            ("France, FR", "France, FR"),
                            ("French Guiana, GF", "French Guiana, GF"),
                            ("French Polynesia, PF", "French Polynesia, PF"),
                            (
                                "French Southern Territories, TF",
                                "French Southern Territories, TF",
                            ),
                            ("Gabon, GA", "Gabon, GA"),
                            ("Gambia, GM", "Gambia, GM"),
                            ("Georgia, GE", "Georgia, GE"),
                            ("Germany, DE", "Germany, DE"),
                            ("Ghana, GH", "Ghana, GH"),
                            ("Gibraltar, GI", "Gibraltar, GI"),
                            ("Greece, GR", "Greece, GR"),
                            ("Greenland, GL", "Greenland, GL"),
                            ("Grenada, GD", "Grenada, GD"),
                            ("Guadeloupe, GP", "Guadeloupe, GP"),
                            ("Guam, GU", "Guam, GU"),
                            ("Guatemala, GT", "Guatemala, GT"),
                            ("Guernsey, GG", "Guernsey, GG"),
                            ("Guinea, GN", "Guinea, GN"),
                            ("Guinea-Bissau, GW", "Guinea-Bissau, GW"),
                            ("Guyana, GY", "Guyana, GY"),
                            ("Haiti, HT", "Haiti, HT"),
                            (
                                "Heard Island and McDonald Islands, HM",
                                "Heard Island and McDonald Islands, HM",
                            ),
                            ("Holy See, VA", "Holy See, VA"),
                            ("Honduras, HN", "Honduras, HN"),
                            ("Hong Kong, HK", "Hong Kong, HK"),
                            ("Hungary, HU", "Hungary, HU"),
                            ("Iceland, IS", "Iceland, IS"),
                            ("India, IN", "India, IN"),
                            ("Indonesia, ID", "Indonesia, ID"),
                            ("Iran, IR", "Iran, IR"),
                            ("Iraq, IQ", "Iraq, IQ"),
                            ("Ireland, IE", "Ireland, IE"),
                            ("Isle of Man, IM", "Isle of Man, IM"),
                            ("Israel, IL", "Israel, IL"),
                            ("Italy, IT", "Italy, IT"),
                            ("Jamaica, JM", "Jamaica, JM"),
                            ("Japan, JP", "Japan, JP"),
                            ("Jersey, JE", "Jersey, JE"),
                            ("Jordan, JO", "Jordan, JO"),
                            ("Kazakhstan, KZ", "Kazakhstan, KZ"),
                            ("Kenya, KE", "Kenya, KE"),
                            ("Kiribati, KI", "Kiribati, KI"),
                            (
                                "Korea (the Democratic People's Republic of), KP",
                                "Korea (the Democratic People's Republic of), KP",
                            ),
                            ("Korea, KR", "Korea, KR"),
                            ("Kuwait, KW", "Kuwait, KW"),
                            ("Kyrgyzstan, KG", "Kyrgyzstan, KG"),
                            (
                                "Lao People's Democratic Republic, LA",
                                "Lao People's Democratic Republic, LA",
                            ),
                            ("Latvia, LV", "Latvia, LV"),
                            ("Lebanon, LB", "Lebanon, LB"),
                            ("Lesotho, LS", "Lesotho, LS"),
                            ("Liberia, LR", "Liberia, LR"),
                            ("Libya, LY", "Libya, LY"),
                            ("Liechtenstein, LI", "Liechtenstein, LI"),
                            ("Lithuania, LT", "Lithuania, LT"),
                            ("Luxembourg, LU", "Luxembourg, LU"),
                            ("Macao, MO", "Macao, MO"),
                            ("Madagascar, MG", "Madagascar, MG"),
                            ("Malawi, MW", "Malawi, MW"),
                            ("Malaysia, MY", "Malaysia, MY"),
                            ("Maldives, MV", "Maldives, MV"),
                            ("Mali, ML", "Mali, ML"),
                            ("Malta, MT", "Malta, MT"),
                            ("Marshall Islands, MH", "Marshall Islands, MH"),
                            ("Martinique, MQ", "Martinique, MQ"),
                            ("Mauritania, MR", "Mauritania, MR"),
                            ("Mauritius, MU", "Mauritius, MU"),
                            ("Mayotte, YT", "Mayotte, YT"),
                            ("Mexico, MX", "Mexico, MX"),
                            ("Micronesia, FM", "Micronesia, FM"),
                            ("Moldova, MD", "Moldova, MD"),
                            ("Monaco, MC", "Monaco, MC"),
                            ("Mongolia, MN", "Mongolia, MN"),
                            ("Montenegro, ME", "Montenegro, ME"),
                            ("Montserrat, MS", "Montserrat, MS"),
                            ("Morocco, MA", "Morocco, MA"),
                            ("Mozambique, MZ", "Mozambique, MZ"),
                            ("Myanmar, MM", "Myanmar, MM"),
                            ("Namibia, NA", "Namibia, NA"),
                            ("Nauru, NR", "Nauru, NR"),
                            ("Nepal, NP", "Nepal, NP"),
                            ("Netherlands, NL", "Netherlands, NL"),
                            ("New Caledonia, NC", "New Caledonia, NC"),
                            ("New Zealand, NZ", "New Zealand, NZ"),
                            ("Nicaragua, NI", "Nicaragua, NI"),
                            ("Niger, NE", "Niger, NE"),
                            ("Nigeria, NG", "Nigeria, NG"),
                            ("Niue, NU", "Niue, NU"),
                            ("Norfolk Island, NF", "Norfolk Island, NF"),
                            (
                                "Northern Mariana Islands, MP",
                                "Northern Mariana Islands, MP",
                            ),
                            ("Norway, NO", "Norway, NO"),
                            ("Oman, OM", "Oman, OM"),
                            ("Pakistan, PK", "Pakistan, PK"),
                            ("Palau, PW", "Palau, PW"),
                            ("Palestine, State of, PS", "Palestine, State of, PS"),
                            ("Panama, PA", "Panama, PA"),
                            ("Papua New Guinea, PG", "Papua New Guinea, PG"),
                            ("Paraguay, PY", "Paraguay, PY"),
                            ("Peru, PE", "Peru, PE"),
                            ("Philippines, PH", "Philippines, PH"),
                            ("Pitcairn, PN", "Pitcairn, PN"),
                            ("Poland, PL", "Poland, PL"),
                            ("Portugal, PT", "Portugal, PT"),
                            ("Puerto Rico, PR", "Puerto Rico, PR"),
                            ("Qatar, QA", "Qatar, QA"),
                            (
                                "Republic of North Macedonia, MK",
                                "Republic of North Macedonia, MK",
                            ),
                            ("Romania, RO", "Romania, RO"),
                            ("Russian Federation, RU", "Russian Federation, RU"),
                            ("Rwanda, RW", "Rwanda, RW"),
                            ("Réunion, RE", "Réunion, RE"),
                            ("Saint Barthélemy, BL", "Saint Barthélemy, BL"),
                            (
                                "Saint Helena, Ascension and Tristan da Cunha, SH",
                                "Saint Helena, Ascension and Tristan da Cunha, SH",
                            ),
                            ("Saint Kitts and Nevis, KN", "Saint Kitts and Nevis, KN"),
                            ("Saint Lucia, LC", "Saint Lucia, LC"),
                            (
                                "Saint Martin (French part), MF",
                                "Saint Martin (French part), MF",
                            ),
                            (
                                "Saint Pierre and Miquelon, PM",
                                "Saint Pierre and Miquelon, PM",
                            ),
                            (
                                "Saint Vincent and the Grenadines, VC",
                                "Saint Vincent and the Grenadines, VC",
                            ),
                            ("Samoa, WS", "Samoa, WS"),
                            ("San Marino, SM", "San Marino, SM"),
                            ("Sao Tome and Principe, ST", "Sao Tome and Principe, ST"),
                            ("Saudi Arabia, SA", "Saudi Arabia, SA"),
                            ("Senegal, SN", "Senegal, SN"),
                            ("Serbia, RS", "Serbia, RS"),
                            ("Seychelles, SC", "Seychelles, SC"),
                            ("Sierra Leone, SL", "Sierra Leone, SL"),
                            ("Singapore, SG", "Singapore, SG"),
                            (
                                "Sint Maarten (Dutch part), SX",
                                "Sint Maarten (Dutch part), SX",
                            ),
                            ("Slovakia, SK", "Slovakia, SK"),
                            ("Slovenia, SI", "Slovenia, SI"),
                            ("Solomon Islands, SB", "Solomon Islands, SB"),
                            ("Somalia, SO", "Somalia, SO"),
                            ("South Africa, ZA", "South Africa, ZA"),
                            (
                                "South Georgia and the South Sandwich Islands, GS",
                                "South Georgia and the South Sandwich Islands, GS",
                            ),
                            ("South Sudan, SS", "South Sudan, SS"),
                            ("Spain, ES", "Spain, ES"),
                            ("Sri Lanka, LK", "Sri Lanka, LK"),
                            ("Sudan, SD", "Sudan, SD"),
                            ("Suriname, SR", "Suriname, SR"),
                            (
                                "Svalbard and Jan Mayen, SJ",
                                "Svalbard and Jan Mayen, SJ",
                            ),
                            ("Sweden, SE", "Sweden, SE"),
                            ("Switzerland, CH", "Switzerland, CH"),
                            ("Syrian Arab Republic, SY", "Syrian Arab Republic, SY"),
                            ("Taiwan, TW", "Taiwan, TW"),
                            ("Tajikistan, TJ", "Tajikistan, TJ"),
                            ("Tanzania, TZ", "Tanzania, TZ"),
                            ("Thailand, TH", "Thailand, TH"),
                            ("Timor-Leste, TL", "Timor-Leste, TL"),
                            ("Togo, TG", "Togo, TG"),
                            ("Tokelau, TK", "Tokelau, TK"),
                            ("Tonga, TO", "Tonga, TO"),
                            ("Trinidad and Tobago, TT", "Trinidad and Tobago, TT"),
                            ("Tunisia, TN", "Tunisia, TN"),
                            ("Turkey, TR", "Turkey, TR"),
                            ("Turkmenistan, TM", "Turkmenistan, TM"),
                            (
                                "Turks and Caicos Islands, TC",
                                "Turks and Caicos Islands, TC",
                            ),
                            ("Tuvalu, TV", "Tuvalu, TV"),
                            ("Uganda, UG", "Uganda, UG"),
                            ("Ukraine, UA", "Ukraine, UA"),
                            ("United Arab Emirates, AE", "United Arab Emirates, AE"),
                            (
                                "United Kingdom of Great Britain and Northern Ireland, GB",
                                "United Kingdom of Great Britain and Northern Ireland, GB",
                            ),
                            (
                                "United States Minor Outlying Islands, UM",
                                "United States Minor Outlying Islands, UM",
                            ),
                            (
                                "United States of America, US",
                                "United States of America, US",
                            ),
                            ("Uruguay, UY", "Uruguay, UY"),
                            ("Uzbekistan, UZ", "Uzbekistan, UZ"),
                            ("Vanuatu, VU", "Vanuatu, VU"),
                            ("Venezuela, VE", "Venezuela, VE"),
                            ("Viet Nam, VN", "Viet Nam, VN"),
                            (
                                "Virgin Islands (British), VG",
                                "Virgin Islands (British), VG",
                            ),
                            ("Virgin Islands (U.S.), VI", "Virgin Islands (U.S.), VI"),
                            ("Wallis and Futuna, WF", "Wallis and Futuna, WF"),
                            ("Western Sahara, EH", "Western Sahara, EH"),
                            ("Yemen, YE", "Yemen, YE"),
                            ("Zambia, ZM", "Zambia, ZM"),
                            ("Zimbabwe, ZW", "Zimbabwe, ZW"),
                            ("Åland Islands, AX", "Åland Islands, AX"),
                        ],
                        default="Afghanistan, AF",
                        max_length=255,
                        verbose_name="Country",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Arabic", "Arabic"),
                            ("Bengali", "Bengali"),
                            ("Chinese (Mandarin)", "Chinese (Mandarin)"),
                            ("English", "English"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Hindi", "Hindi"),
                            ("Italian", "Italian"),
                            ("Japanese", "Japanese"),
                            ("Korean", "Korean"),
                            ("Portuguese", "Portuguese"),
                            ("Russian", "Russian"),
                            ("Spanish", "Spanish"),
                            ("Tamil", "Tamil"),
                            ("Telugu", "Telugu"),
                            ("Turkish", "Turkish"),
                            ("Other", "Other"),
                        ],
                        default="Arabic",
                        max_length=255,
                        verbose_name="Language",
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=512, verbose_name="City"),
                ),
                (
                    "street",
                    models.CharField(default="", max_length=512, verbose_name="Street"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        default="", max_length=255, verbose_name="Postal Code"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=255, verbose_name="Contact Phone"),
                ),
                (
                    "company",
                    models.CharField(
                        default="", max_length=255, verbose_name="Company"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Company Name"
                    ),
                ),
                (
                    "fiskal_id_number",
                    models.CharField(
                        default="", max_length=255, verbose_name="Fiskal ID Number"
                    ),
                ),
                (
                    "country_phone",
                    models.CharField(
                        default="", max_length=255, verbose_name="Country Phone"
                    ),
                ),
                (
                    "company_contact_phone",
                    models.CharField(
                        max_length=255, verbose_name="Company Contact Phone"
                    ),
                ),
                ("pan", models.CharField(max_length=255, verbose_name="PAN")),
                (
                    "gst_number",
                    models.CharField(
                        default="", max_length=255, verbose_name="GST Number"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Account Name"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default="", max_length=255, verbose_name="Account Number"
                    ),
                ),
                (
                    "ifsc",
                    models.CharField(default="", max_length=255, verbose_name="IFSC"),
                ),
                (
                    "sort_code",
                    models.CharField(
                        default="", max_length=255, verbose_name="SORT Code"
                    ),
                ),
                (
                    "swift_code",
                    models.CharField(
                        default="", max_length=255, verbose_name="Swift Code"
                    ),
                ),
                (
                    "iban",
                    models.CharField(default="", max_length=255, verbose_name="IBAN"),
                ),
                (
                    "bank_country",
                    models.CharField(
                        default="", max_length=255, verbose_name="Bank Country"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Bank Name"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="DueAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Amount Due")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="due_amounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Due Amount",
                "verbose_name_plural": "Due Amounts",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="Username")),
                ("date_of_payment", models.DateField(verbose_name="Payment Date")),
                ("amount_paid", models.FloatField(verbose_name="Amount Paid")),
                ("tds", models.FloatField(verbose_name="TDS")),
                (
                    "tds_percentage",
                    models.BigIntegerField(verbose_name="TDS Percentage"),
                ),
                (
                    "source_account",
                    models.CharField(max_length=400, verbose_name="Source Account"),
                ),
                (
                    "sent_to_name",
                    models.CharField(max_length=400, verbose_name="Recipient Name"),
                ),
                (
                    "sent_to_account_number",
                    models.CharField(max_length=400, verbose_name="Account Number"),
                ),
                (
                    "sent_to_ifsc_code",
                    models.CharField(max_length=400, verbose_name="IFSC Code"),
                ),
                (
                    "transfer_id",
                    models.CharField(max_length=400, verbose_name="Transfer ID"),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "indexes": [
                    models.Index(
                        fields=["username"], name="main_paymen_usernam_a5daf9_idx"
                    ),
                    models.Index(
                        fields=["date_of_payment"],
                        name="main_paymen_date_of_65e39e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Ratio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stores", models.IntegerField()),
                ("youtube", models.IntegerField()),
                ("sales_payout", models.IntegerField()),
                ("sales_payout_threshold", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "In Active")],
                        default="active",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ratio",
                "verbose_name_plural": "Ratios",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="Title"),
                ),
                (
                    "description",
                    models.CharField(
                        default="", max_length=5000, verbose_name="Description"
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        default="", max_length=5000, verbose_name="Admin Feedback"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("IN REVIEW", "IN REVIEW"),
                            ("CLOSED", "CLOSED"),
                        ],
                        default="PENDING",
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
            },
        ),
        migrations.CreateModel(
            name="Sharing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Store Revenue Share (%)",
                    ),
                ),
                (
                    "youtube_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="YouTube Revenue Share (%)",
                    ),
                ),
                (
                    "payout_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Payout Threshold (INR)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sharing",
                "verbose_name_plural": "Shares",
            },
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["email"], name="main_cduser_email_10f11f_idx"),
        ),
        migrations.AddIndex(
            model_name="sharing",
            index=models.Index(fields=["user"], name="main_sharin_user_id_0615c2_idx"),
        ),
        migrations.AddIndex(
            model_name="sharing",
            index=models.Index(
                fields=["is_active"], name="main_sharin_is_acti_f63122_idx"
            ),
        ),
    ]
