# Generated by Django 4.2.21 on 2025-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cduser",
            name="split_royalties_enabled",
            field=models.BooleanField(default=False, verbose_name="Split Royalties"),
        ),
    ]
