# Generated by Django 5.2.2 on 2025-06-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_cduser_split_royalties_enabled"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cduser",
            new_name="email_index",
            old_name="main_cduser_email_10f11f_idx",
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["role"], name="role_index"),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["is_active"], name="is_active_index"),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["is_superuser"], name="is_superuser_index"),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["is_staff"], name="is_staff_index"),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(
                fields=["split_royalties_enabled"], name="split_royalties_enabled_index"
            ),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["country"], name="country_index"),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(fields=["language"], name="language_index"),
        ),
        migrations.AddIndex(
            model_name="dueamount",
            index=models.Index(fields=["amount"], name="main_dueamo_amount_7a29c4_idx"),
        ),
        migrations.AddIndex(
            model_name="dueamount",
            index=models.Index(
                fields=["created_at"], name="main_dueamo_created_b192ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dueamount",
            index=models.Index(
                fields=["updated_at"], name="main_dueamo_updated_0f85d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["amount_paid"], name="main_paymen_amount__7bfc84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["tds"], name="main_paymen_tds_f1803f_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tds_percentage"], name="main_paymen_tds_per_35a206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transfer_id"], name="main_paymen_transfe_be42e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(fields=["stores"], name="main_ratio_stores_9f5eb7_idx"),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(
                fields=["youtube"], name="main_ratio_youtube_260f0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(
                fields=["sales_payout"], name="main_ratio_sales_p_0376ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(
                fields=["sales_payout_threshold"], name="main_ratio_sales_p_7fe9a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(fields=["status"], name="main_ratio_status_55ef3c_idx"),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(
                fields=["created_at"], name="main_ratio_created_ca537e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(
                fields=["updated_at"], name="main_ratio_updated_a87109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["title"], name="main_reques_title_b7346a_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["status"], name="main_reques_status_e0feb6_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["created_at"], name="main_reques_created_092f13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["updated_at"], name="main_reques_updated_254f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharing",
            index=models.Index(
                fields=["created_at"], name="main_sharin_created_f7d842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharing",
            index=models.Index(
                fields=["updated_at"], name="main_sharin_updated_1a57e1_idx"
            ),
        ),
    ]
