# Generated by Django 5.2.2 on 2025-07-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_main_cduser_email_10f11f_idx_email_index_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(
                fields=["parent"], name="main_cduser_parent__85b1a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(
                fields=["date_joined"], name="main_cduser_date_jo_2142a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cduser",
            index=models.Index(
                fields=["role", "is_active"], name="main_cduser_role_9af1c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dueamount",
            index=models.Index(fields=["user"], name="main_dueamo_user_id_b4158f_idx"),
        ),
        migrations.AddIndex(
            model_name="ratio",
            index=models.Index(fields=["user"], name="main_ratio_user_id_6698e1_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["user"], name="main_reques_user_id_aefc90_idx"),
        ),
    ]
