# Generated by Django 4.2.27 on 2026-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cduser_main_cduser_parent__85b1a5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cduser',
            name='language',
            field=models.CharField(choices=[('Afrikaans', 'Afrikaans'), ('Amharic', 'Amharic'), ('Arabic', 'Arabic'), ('Arabic - Egyptian', 'Arabic - Egyptian'), ('Arabic - Moroccan', 'Arabic - Moroccan'), ('Armenian', 'Armenian'), ('Assamese', 'Assamese'), ('Azerbaijani', 'Azerbaijani'), ('Basque', 'Basque'), ('Belarusian', 'Belarusian'), ('Bengali', 'Bengali'), ('Bhojpuri', 'Bhojpuri'), ('Bosnian', 'Bosnian'), ('Bulgarian', 'Bulgarian'), ('Cambodian', 'Cambodian'), ('Catalan', 'Catalan'), ('Chechen', 'Chechen'), ('Chinese', 'Chinese'), ('Chinese - Cantonese', 'Chinese - Cantonese'), ('Chinese - Hakka', 'Chinese - Hakka'), ('Chinese - Mandarin', 'Chinese - Mandarin'), ('Croatian', 'Croatian'), ('Czech', 'Czech'), ('Danish', 'Danish'), ('Dutch', 'Dutch'), ('English', 'English'), ('Estonian', 'Estonian'), ('Filipino', 'Filipino'), ('Finnish', 'Finnish'), ('French', 'French'), ('Galician', 'Galician'), ('Georgian', 'Georgian'), ('German', 'German'), ('Greek', 'Greek'), ('Gujarati', 'Gujarati'), ('Haitian', 'Haitian'), ('Haitian Creole', 'Haitian Creole'), ('Haryanvi', 'Haryanvi'), ('Hawaiian', 'Hawaiian'), ('Hebrew', 'Hebrew'), ('Hindi', 'Hindi'), ('Hungarian', 'Hungarian'), ('Icelandic', 'Icelandic'), ('Igbo', 'Igbo'), ('Indonesian', 'Indonesian'), ('Irish', 'Irish'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Kannada', 'Kannada'), ('Kazakh', 'Kazakh'), ('Konkani', 'Konkani'), ('Korean', 'Korean'), ('Kurdish', 'Kurdish'), ('Lao', 'Lao'), ('Latin', 'Latin'), ('Latvian', 'Latvian'), ('Lingala', 'Lingala'), ('Lithuanian', 'Lithuanian'), ('Luganda', 'Luganda'), ('Macedonian', 'Macedonian'), ('Malay', 'Malay'), ('Malayalam', 'Malayalam'), ('Maori', 'Maori'), ('Marathi', 'Marathi'), ('Mongolian', 'Mongolian'), ('Nepali', 'Nepali'), ('Norwegian', 'Norwegian'), ('Oriya', 'Oriya'), ('Persian', 'Persian'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Punjabi', 'Punjabi'), ('Rajasthani', 'Rajasthani'), ('Romanian', 'Romanian'), ('Russian', 'Russian'), ('Samoan', 'Samoan'), ('Sanskrit', 'Sanskrit'), ('Sepedi', 'Sepedi'), ('Serbian', 'Serbian'), ('Shona', 'Shona'), ('Slovak', 'Slovak'), ('Slovene', 'Slovene'), ('Sotho', 'Sotho'), ('Spanish', 'Spanish'), ('Swahili', 'Swahili'), ('Swedish', 'Swedish'), ('Tagalog', 'Tagalog'), ('Tahitian', 'Tahitian'), ('Tamazight', 'Tamazight'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Thai', 'Thai'), ('Tsonga', 'Tsonga'), ('Tswana', 'Tswana'), ('Turkish', 'Turkish'), ('Twi', 'Twi'), ('Ukrainian', 'Ukrainian'), ('Urdu', 'Urdu'), ('Venda', 'Venda'), ('Vietnamese', 'Vietnamese'), ('Xhosa', 'Xhosa'), ('Zulu', 'Zulu')], default='Afrikaans', max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='cduser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('intermediate', 'Intermediate'), ('normal', 'Normal'), ('member', 'Member'), ('split_recipient', 'Split Recipient')], default='normal', max_length=20),
        ),
    ]
