# Generated by Django 4.2.27 on 2026-03-30 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cduser_apple_music_dolby_atmos_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoyaltyUserExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('batch_id', models.UUIDField(db_index=True, editable=False)),
                ('s3_key', models.CharField(max_length=512)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('batch_label', models.CharField(blank=True, default='', help_text='Optional label from admin upload form.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_user_exports_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_email', 'expires_at'], name='main_royalt_owner_e_dcee49_idx'), models.Index(fields=['batch_id'], name='main_royalt_batch_i_cbd853_idx')],
            },
        ),
    ]
