# Generated by Django 4.2.27 on 2026-03-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_royalty_user_export'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='royaltyuserexport',
            options={'ordering': ['-report_period', '-created_at']},
        ),
        migrations.AddField(
            model_name='royaltyuserexport',
            name='report_period',
            field=models.DateField(blank=True, db_index=True, help_text='First day of confirmed sales month (e.g. 2026-02-01 = February 2026).', null=True),
        ),
        migrations.AlterField(
            model_name='royaltyuserexport',
            name='batch_label',
            field=models.CharField(blank=True, default='', help_text='Optional extra label from admin upload form.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='royaltyuserexport',
            index=models.Index(fields=['owner_email', 'report_period'], name='main_royalt_owner_e_4c3ade_idx'),
        ),
    ]
