COUNTRIES = [
    "Afghanistan, AF",
    "Albania, AL",
    "Algeria, DZ",
    "American Samoa, AS",
    "Andorra, AD",
    "Angola, AO",
    "Anguilla, AI",
    "Antarctica, AQ",
    "Antigua and Barbuda, AG",
    "Argentina, AR",
    "Armenia, AM",
    "Aruba, AW",
    "Australia, AU",
    "Austria, AT",
    "Azerbaijan, AZ",
    "Bahamas, BS",
    "Bahrain, BH",
    "Bangladesh, BD",
    "Barbados, BB",
    "Belarus, BY",
    "Belgium, BE",
    "Belize, BZ",
    "Benin, BJ",
    "Bermuda, BM",
    "Bhutan, BT",
    "Bolivia, BO",
    "Bonaire, Sint Eustatius and Saba, BQ",
    "Bosnia and Herzegovina, BA",
    "Botswana, BW",
    "Bouvet Island, BV",
    "Brazil, BR",
    "British Indian Ocean Territory, IO",
    "Brunei Darussalam, BN",
    "Bulgaria, BG",
    "Burkina Faso, BF",
    "Burundi, BI",
    "Cabo Verde, CV",
    "Cambodia, KH",
    "Cameroon, CM",
    "Canada, CA",
    "Cayman Islands, KY",
    "Central African Republic, CF",
    "Chad, TD",
    "Chile, CL",
    "China, CN",
    "Christmas Island, CX",
    "Cocos Islands, CC",
    "Colombia, CO",
    "Comoros, KM",
    "Congo, CD",
    "Congo, CG",
    "Cook Islands, CK",
    "Costa Rica, CR",
    "Croatia, HR",
    "Cuba, CU",
    "Curaçao, CW",
    "Cyprus, CY",
    "Czechia, CZ",
    "Côte d'Ivoire, CI",
    "Denmark, DK",
    "Djibouti, DJ",
    "Dominica, DM",
    "Dominican Republic, DO",
    "Ecuador, EC",
    "Egypt, EG",
    "El Salvador, SV",
    "Equatorial Guinea, GQ",
    "Eritrea, ER",
    "Estonia, EE",
    "Eswatini, SZ",
    "Ethiopia, ET",
    "Falkland Islands [Malvinas], FK",
    "Faroe Islands, FO",
    "Fiji, FJ",
    "Finland, FI",
    "France, FR",
    "French Guiana, GF",
    "French Polynesia, PF",
    "French Southern Territories, TF",
    "Gabon, GA",
    "Gambia, GM",
    "Georgia, GE",
    "Germany, DE",
    "Ghana, GH",
    "Gibraltar, GI",
    "Greece, GR",
    "Greenland, GL",
    "Grenada, GD",
    "Guadeloupe, GP",
    "Guam, GU",
    "Guatemala, GT",
    "Guernsey, GG",
    "Guinea, GN",
    "Guinea-Bissau, GW",
    "Guyana, GY",
    "Haiti, HT",
    "Heard Island and McDonald Islands, HM",
    "Holy See, VA",
    "Honduras, HN",
    "Hong Kong, HK",
    "Hungary, HU",
    "Iceland, IS",
    "India, IN",
    "Indonesia, ID",
    "Iran, IR",
    "Iraq, IQ",
    "Ireland, IE",
    "Isle of Man, IM",
    "Israel, IL",
    "Italy, IT",
    "Jamaica, JM",
    "Japan, JP",
    "Jersey, JE",
    "Jordan, JO",
    "Kazakhstan, KZ",
    "Kenya, KE",
    "Kiribati, KI",
    "Korea (the Democratic People's Republic of), KP",
    "Korea, KR",
    "Kuwait, KW",
    "Kyrgyzstan, KG",
    "Lao People's Democratic Republic, LA",
    "Latvia, LV",
    "Lebanon, LB",
    "Lesotho, LS",
    "Liberia, LR",
    "Libya, LY",
    "Liechtenstein, LI",
    "Lithuania, LT",
    "Luxembourg, LU",
    "Macao, MO",
    "Madagascar, MG",
    "Malawi, MW",
    "Malaysia, MY",
    "Maldives, MV",
    "Mali, ML",
    "Malta, MT",
    "Marshall Islands, MH",
    "Martinique, MQ",
    "Mauritania, MR",
    "Mauritius, MU",
    "Mayotte, YT",
    "Mexico, MX",
    "Micronesia, FM",
    "Moldova, MD",
    "Monaco, MC",
    "Mongolia, MN",
    "Montenegro, ME",
    "Montserrat, MS",
    "Morocco, MA",
    "Mozambique, MZ",
    "Myanmar, MM",
    "Namibia, NA",
    "Nauru, NR",
    "Nepal, NP",
    "Netherlands, NL",
    "New Caledonia, NC",
    "New Zealand, NZ",
    "Nicaragua, NI",
    "Niger, NE",
    "Nigeria, NG",
    "Niue, NU",
    "Norfolk Island, NF",
    "Northern Mariana Islands, MP",
    "Norway, NO",
    "Oman, OM",
    "Pakistan, PK",
    "Palau, PW",
    "Palestine, State of, PS",
    "Panama, PA",
    "Papua New Guinea, PG",
    "Paraguay, PY",
    "Peru, PE",
    "Philippines, PH",
    "Pitcairn, PN",
    "Poland, PL",
    "Portugal, PT",
    "Puerto Rico, PR",
    "Qatar, QA",
    "Republic of North Macedonia, MK",
    "Romania, RO",
    "Russian Federation, RU",
    "Rwanda, RW",
    "Réunion, RE",
    "Saint Barthélemy, BL",
    "Saint Helena, Ascension and Tristan da Cunha, SH",
    "Saint Kitts and Nevis, KN",
    "Saint Lucia, LC",
    "Saint Martin (French part), MF",
    "Saint Pierre and Miquelon, PM",
    "Saint Vincent and the Grenadines, VC",
    "Samoa, WS",
    "San Marino, SM",
    "Sao Tome and Principe, ST",
    "Saudi Arabia, SA",
    "Senegal, SN",
    "Serbia, RS",
    "Seychelles, SC",
    "Sierra Leone, SL",
    "Singapore, SG",
    "Sint Maarten (Dutch part), SX",
    "Slovakia, SK",
    "Slovenia, SI",
    "Solomon Islands, SB",
    "Somalia, SO",
    "South Africa, ZA",
    "South Georgia and the South Sandwich Islands, GS",
    "South Sudan, SS",
    "Spain, ES",
    "Sri Lanka, LK",
    "Sudan, SD",
    "Suriname, SR",
    "Svalbard and Jan Mayen, SJ",
    "Sweden, SE",
    "Switzerland, CH",
    "Syrian Arab Republic, SY",
    "Taiwan, TW",
    "Tajikistan, TJ",
    "Tanzania, United Republic of, TZ",
    "Thailand, TH",
    "Timor-Leste, TL",
    "Togo, TG",
    "Tokelau, TK",
    "Tonga, TO",
    "Trinidad and Tobago, TT",
    "Tunisia, TN",
    "Turkey, TR",
    "Turkmenistan, TM",
    "Turks and Caicos Islands, TC",
    "Tuvalu, TV",
    "Uganda, UG",
    "Ukraine, UA",
    "United Arab Emirates, AE",
    "United Kingdom of Great Britain and Northern Ireland, GB",
    "United States Minor Outlying Islands, UM",
    "United States of America, US",
    "Uruguay, UY",
    "Uzbekistan, UZ",
    "Vanuatu, VU",
    "Venezuela (Bolivarian Republic of), VE",
    "Viet Nam, VN",
    "Virgin Islands (British), VG",
    "Virgin Islands (U.S.), VI",
    "Wallis and Futuna, WF",
    "Western Sahara, EH",
    "Yemen, YE",
    "Zambia, ZM",
    "Zimbabwe, ZW",
    "Åland Islands, AX",
]
LANGUAGES = [
    "Afrikaans",
    "Arabic",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bulgarian",
    "Cambodian",
    "Cantonese",
    "Catalan",
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Haitian",
    "Haryanvi",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Icelandic",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Kazakh",
    "Korean",
    "Lao",
    "Latin",
    "Latvian",
    "Lithuanian",
    "Luganda",
    "Malay",
    "Mongolian",
    "Nepali",
    "Norwegian",
    "Oriya",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Slovak",
    "Slovene",
    "Spanish",
    "Swedish",
    "Tagalog",
    "Tamazight",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Zulu",
]
GENRES = [
    "Alternative",
    "Alternative/Experimental",
    "Alternative/Gothic",
    "Alternative/Grunge",
    "Alternative/Indie Pop",
    "Alternative/Indie Rock",
    "Alternative/Rock",
    "Ambient/New Age",
    "Ambient/New Age/Meditation",
    "Blues",
    "Blues/Contemporary Blues",
    "Blues/New Orleans Blues",
    "Blues/Traditional Blues",
    "Childrens Music",
    "Childrens Music/Classic",
    "Childrens Music/Holiday",
    "Childrens Music/Stories",
    "Classical",
    "Classical/Antique",
    "Classical/Baroque",
    "Classical/Chamber",
    "Classical/Concert",
    "Classical/Modern Compositions",
    "Classical/Opera",
    "Classical/Orchestral",
    "Classical/Piano",
    "Classical/Romantic",
    "Comedy",
    "Country",
    "Country/Bluegrass",
    "Country/Contemporary",
    "Country/Honky Tonk",
    "Country/Nashville",
    "Country/Pop",
    "Country/Square Dance",
    "Easy Listening",
    "Easy Listening/BarJazz/Cocktail",
    "Easy Listening/Bossa Nova",
    "Easy Listening/Lounge",
    "Easy Listening/Traditional",
    "Electronic",
    "Electronic/Acid House",
    "Electronic/Breaks",
    "Electronic/Broken beat",
    "Electronic/Chill Out",
    "Electronic/DJ Tools/SamplePacks",
    "Electronic/Dance",
    "Electronic/Deep House",
    "Electronic/Downtempo -experimental",
    "Electronic/Drum & Bass",
    "Electronic/Dub/Reggae/Dancehall",
    "Electronic/Dubstep/Grime",
    "Electronic/Electro House",
    "Electronic/Glitch Hop",
    "Electronic/Hard Dance",
    "Electronic/Hard Techno",
    "Electronic/Hardcore",
    "Electronic/Hardstyle",
    "Electronic/House",
    "Electronic/Indie Dance/Nu Disco",
    "Electronic/Jazz",
    "Electronic/Minimal",
    "Electronic/Pop Trance",
    "Electronic/Progressive House",
    "Electronic/Psy-Trance",
    "Electronic/Tech House",
    "Electronic/Techno",
    "Electronic/Trance",
    "Electronic/Trip Hop",
    "Experimental",
    "Fitness&Workout",
    "Flamenco",
    "Folk",
    "Funk/R&B",
    "Hip-Hop/Rap",
    "Hip-Hop/Rap/Gangsta & Hardcore",
    "Holiday/Christmas",
    "Inspirational",
    "Jazz",
    "Jazz/Bebop",
    "Jazz/Big Band",
    "Jazz/Brazilian Jazz",
    "Jazz/Classic",
    "Jazz/Contemporary",
    "Jazz/Dixie/Rag Time",
    "Jazz/Free Jazz",
    "Jazz/Fusion",
    "Jazz/Jazz Funk",
    "Jazz/Latin Jazz",
    "Jazz/Nu Jazz/Acid Jazz",
    "Jazz/Smooth Jazz",
    "Jazz/Swing",
    "Jazz/Traditional",
    "Jazz/World",
    "Karaoke",
    "Latin",
    "Latin/Bachata",
    "Latin/Banda",
    "Latin/Big Band",
    "Latin/Bolero",
    "Latin/Bossa Nova",
    "Latin/Brasil/Tropical",
    "Latin/Christian",
    "Latin/Conjunto",
    "Latin/Corridos",
    "Latin/Cuban",
    "Latin/Cumbia",
    "Latin/Duranguense",
    "Latin/Electronica",
    "Latin/Grupero",
    "Latin/Hip Hop",
    "Latin/Latin Rap",
    "Latin/Mambo",
    "Latin/Mariachi",
    "Latin/Norteño",
    "Latin/Pop",
    "Latin/Ranchera",
    "Latin/Reggaeton",
    "Latin/Regional Mexicano",
    "Latin/Rock en Español",
    "Latin/Salsa",
    "Latin/Salsa/Merengue",
    "Latin/Sierreño",
    "Latin/Sonidero",
    "Latin/Tango",
    "Latin/Tejano",
    "Latin/Tierra Caliente",
    "Latin/Traditional Mexican",
    "Latin/Vallenato",
    "New Age",
    "Pop",
    "Pop/Contemporary/Adult",
    "Pop/J-Pop",
    "Pop/K-Pop",
    "Pop/Mandopop",
    "Pop/Singer Songwriter",
    "Punk",
    "R&B",
    "Reggae",
    "Rock",
    "Rock/Brit-Pop",
    "Rock/Classic",
    "Rock/Glam Rock",
    "Rock/Hard Rock/Heavy Metal",
    "Rock/Heavy Metal",
    "Rock/Progressive",
    "Rock/Rock 'n' Roll",
    "Rock/Singer/Songwriter",
    "Ska",
    "Soul",
    "Soundtrack",
    "Soundtrack/Anime",
    "Soundtrack/Musical",
    "Soundtrack/TV",
    "Spiritual",
    "Spiritual/Christian",
    "Spiritual/Gospel",
    "Spiritual/Gregorian",
    "Spiritual/India",
    "Spiritual/Judaica",
    "Spiritual/World",
    "Spoken Word/Speeches",
    "Trap",
    "Trap/Future Bass",
    "Trap/Future Bass/Twerk",
    "Vocal/Nostalgia",
    "World",
    "World/African",
    "World/Afro-Beat",
    "World/Afro-Pop",
    "World/Americas/Argentina",
    "World/Americas/Brazilian",
    "World/Americas/Brazilian/Axé",
    "World/Americas/Brazilian/Black Music",
    "World/Americas/Brazilian/Bossa Nova",
    "World/Americas/Brazilian/Chorinho",
    "World/Americas/Brazilian/Folk",
    "World/Americas/Brazilian/Funk Carioca",
    "World/Americas/Brazilian/MPB",
    "World/Americas/Brazilian/Marchinha",
    "World/Americas/Brazilian/Pagode",
    "World/Americas/Brazilian/Samba",
    "World/Americas/Brazilian/Samba-Rock",
    "World/Americas/Brazilian/Samba-de-Raiz",
    "World/Americas/Brazilian/Samba-enredo",
    "World/Americas/Brazilian/Sambalanço",
    "World/Americas/Cajun-Creole",
    "World/Americas/Calypso",
    "World/Americas/Colombia",
    "World/Americas/Cuba-Caribbean",
    "World/Americas/Mexican",
    "World/Americas/North-American",
    "World/Americas/Panama",
    "World/Americas/Peru",
    "World/Americas/South-American",
    "World/Arabic",
    "World/Asian/Central Asia",
    "World/Asian/China",
    "World/Asian/Indian",
    "World/Asian/India-Bollywood",
    "World/Asian/Japan",
    "World/Asian/South Asia",
    "World/Australian/Pacific",
    "World/Ethnic",
    "World/Europe/Eastern",
    "World/Europe/French",
    "World/Europe/German",
    "World/Europe/Northern",
    "World/Europe/Southern",
    "World/Europe/Spain",
    "World/Europe/Western",
    "World/Mediterranean/Greece",
    "World/Mediterranean/Italy",
    "World/Mediterranean/Spain",
    "World/Russian",
    "World/Worldbeat",
]
ARTIST_ROLES = [
    "Primary Artist",
    "Performer",
    "Producer",
    "Remixer",
    "Composer",
    "Lyricist",
    "Featuring",
    "with",
    "Conductor",
    "Arranger",
    "Orchestra",
    "Actor",
    "Xylophone",
    "Whistle",
    "Vocals",
    "Violin",
    "Viola De Gamba",
    "Viola",
    "Trumpet",
    "Trombone",
    "Tambourine",
    "Synthesizer",
    "Saxophone",
    "Recorder",
    "Rap",
    "Programming",
    "Piano",
    "Percussion",
    "Organ",
    "Oboe",
    "Metallophone",
    "Lute",
    "Keyboards",
    "Horn",
    "Harp",
    "Harmonica",
    "Guitar",
    "Flute",
    "Fiddle",
    "Ensemble",
    "Drums",
    "Clarinet",
    "Choir",
    "Cello",
    "Bells",
]
