release_validations = {
    "name": "release",
    "required_columns": [
        "release_upc_code",
        "release_title",
        "release_remix_version",
        "release_artists",
        "release_label",
        "release_primary_genre",
        "release_secondary_genre",
        "release_language",
        "album_format",
        "reference_number",
        "grid",
        "release_description",
        "release_created_by",
    ],
    "db_mapping": {
        "release_upc_code": "upc_code",
        "release_title": "title",
        "release_artists": "artist",
        "release_label": "label",
        "release_primary_genre": "primary_genre",
        "release_language": "language",
        "release_created_by": "created_by",
        "release_remix_version": "remix_version",
        "release_secondary_genre": "secondary_genre",
        "grid": "gr_id",
    },
    "not_null_fields": [
        "release_upc_code",
        "release_title",
        "release_artists",
        "release_label",
        "release_primary_genre",
        "release_language",
        "album_format",
        "release_created_by",
    ],
    "field_formats": {
        "release_created_by": r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        "release_artists": r"([A-Za-z0-9\s]+)\s+\(([^)]+)\)",
    },
    "validation_text": [
        '<p style="text-align: left"><b>File format</b>: .xlsx<br>'
        "<b>Required columns</b>: release_upc_code,release_title,release_remix_version,release_artists,release_label,release_primary_genre,release_secondary_genre,release_language,album_format,reference_number,grid,release_description,release_created_by,track_remix_version,track_title,track_created_by,track_artists,track_primary_genre,track_secondary_genre,track_isrc_code,track_iswc_code,track_publishing_rights_owner,track_publishing_rights_year,track_lyrics,track_explicit_lyrics,track_language,track_available_separately,track_notes,licenses_price_category,licenses_digital_release_date,licenses_original_release_date,licenses_type,licenses_holder_year,licenses_holder_name,licenses_copyright_recording_year,licenses_copyright_recording_text,licenses_territories<br>",
        "<b>Non-Empty columns</b>: release_upc_code,release_title,release_artists,release_label,release_primary_genre,release_language,album_format,release_created_by,track_title,track_created_by,track_artists,track_primary_genre,track_isrc_code,track_publishing_rights_owner,track_publishing_rights_year,track_explicit_lyrics,track_language,licenses_price_category,licenses_digital_release_date,licenses_original_release_date,licenses_type,licenses_holder_year,licenses_holder_name,licenses_copyright_recording_year,licenses_copyright_recording_text<br><br>"
        "<b>All UPC/ISRC codes must be new, and must not be present in the database.</b></p>",
    ],
}

track_validations = {
    "name": "track",
    "required_columns": [
        "track_remix_version",
        "track_title",
        "track_created_by",
        "track_artists",
        "track_primary_genre",
        "track_secondary_genre",
        "track_isrc_code",
        "track_iswc_code",
        "track_publishing_rights_owner",
        "track_publishing_rights_year",
        "track_lyrics",
        "track_explicit_lyrics",
        "track_language",
        "track_available_separately",
        "track_notes",
    ],
    "db_mapping": {
        "track_title": "title",
        "track_created_by": "created_by",
        "track_artists": "artist",
        "track_primary_genre": "primary_genere",
        "track_isrc_code": "isrc_code",
        "track_publishing_rights_owner": "publishing_rights_owner",
        "track_publishing_rights_year": "publishing_rights_year",
        "track_explicit_lyrics": "explicit_lyrics",
        "track_language": "language",
        "track_available_separately": "available_separately",
        "track_remix_version": "remix_version",
        "track_secondary_genre": "secondary_genere",
        "track_iswc_code": "iswc_code",
        "track_lyrics": "lyrics",
        "track_start_point": "start_point",
        "track_notes": "notes",
    },
    "not_null_fields": [
        "track_title",
        "track_created_by",
        "track_artists",
        "track_primary_genre",
        "track_isrc_code",
        "track_publishing_rights_owner",
        "track_publishing_rights_year",
        "track_explicit_lyrics",
        "track_language",
    ],
    "field_formats": {
        "track_created_by": r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$",
        "track_artists": r"([A-Za-z0-9\s]+)\s+\(([^)]+)\)",
        "track_publishing_rights_year": r"\b\d{4}\b",
    },
}

license_validations = {
    "name": "license",
    "required_columns": [
        "licenses_price_category",
        "licenses_digital_release_date",
        "licenses_original_release_date",
        "licenses_type",
        "licenses_holder_year",
        "licenses_holder_name",
        "licenses_copyright_recording_year",
        "licenses_copyright_recording_text",
        "licenses_territories",
    ],
    "db_mapping": {
        "licenses_price_category": "price_category",
        "licenses_digital_release_date": "digital_release_date",
        "licenses_original_release_date": "original_release_date",
        "licenses_type": "license_type",
        "licenses_holder_year": "license_holder_year",
        "licenses_holder_name": "license_holder_name",
        "licenses_copyright_recording_year": "copyright_recording_year",
        "licenses_copyright_recording_text": "copyright_recording_text",
        "licenses_territories": "territories",
    },
    "not_null_fields": [
        "licenses_price_category",
        "licenses_digital_release_date",
        "licenses_original_release_date",
        "licenses_type",
        "licenses_holder_year",
        "licenses_holder_name",
        "licenses_copyright_recording_year",
        "licenses_copyright_recording_text",
    ],
    "field_formats": {
        "licenses_holder_year": r"\b\d{4}\b",
        "licenses_copyright_recording_year": r"\b\d{4}\b",
        "licenses_digital_release_date": r"\b\d{4}-\d{2}-\d{2}\b",
        "licenses_original_release_date": r"\b\d{4}-\d{2}-\d{2}\b",
    },
}

royalties_validations = {
    "name": "royalties",
    "required_columns": [
        "start_date",
        "end_date",
        "country",
        "currency",
        "type",
        "units",
        "unit_price",
        "gross_total",
        "channel_costs",
        "taxes",
        "net_total",
        "currency_rate",
        "gross_total_client_currency",
        "other_costs_client_currency",
        "channel_costs_client_currency",
        "taxes_client_currency",
        "net_total_client_currency",
        "channel",
        "isrc",
    ],
    "not_null_fields": [
        "start_date",
        "end_date",
        "country",
        "currency",
        "type",
        "units",
        "unit_price",
        "gross_total",
        "channel_costs",
        "taxes",
        "net_total",
        "currency_rate",
        "gross_total_client_currency",
        "other_costs_client_currency",
        "channel_costs_client_currency",
        "taxes_client_currency",
        "net_total_client_currency",
        "channel",
        "isrc",
    ],
    "field_formats": {
        "start_date": r"\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2})?)?",
        "end_date": r"\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(\+\d{2}:\d{2})?)?",
    },
    "validation_text": [
        '<p style="text-align: left"><b>File format</b>: .xlsx<br>'
        "<b>Required columns</b>: start_date,end_date,country,currency,type,units,unit_price,gross_total,channel_costs,taxes,net_total,currency_rate,gross_total_client_currency,other_costs_client_currency,channel_costs_client_currency,taxes_client_currency,net_total_client_currency,channel,isrc,user,label,display_artist,release,upc,track<br>",
        "<b>Non-Empty columns</b>: start_date,end_date,country,currency,type,units,unit_price,gross_total,channel_costs,taxes,net_total,currency_rate,gross_total_client_currency,other_costs_client_currency,channel_costs_client_currency,taxes_client_currency,net_total_client_currency,channel,isrc,user</p>",
    ],
}

royalties_meta_validations = {
    "name": "royalties_meta",
    "required_columns": [
        "isrc",
        "user",
        "label",
        "display_artist",
        "release",
        "upc",
        "track",
    ],
    "not_null_fields": [
        "isrc",
        "user",
        "label",
        "display_artist",
        "release",
        "upc",
        "track",
    ],
    "field_formats": {},
}

royalties_type_mappings = {
    "AIRTEL RBT": "streams",
    "AMAZON PRIME": "streams",
    "FACEBOOK AND INSTAGRAM": "videos",
    "JIOSAAVN": "streams",
    "FACEBOOK UGC CLAIMS": "views",
    "KKBOX": "streams",
    "APPLE MUSIC": "streams",
    "GAANA": "streams",
    "AMAZON UNLIMITED MUSIC": "streams",
    "YOUTUBE ARTTRACK": "views",
    "YOUTUBE AUDIO CONTENT ID": "views",
    "HUNGAMA": "streams",
    "YOUTUBE OFFICIAL CHANNEL": "views",
    "YOUTUBE MUSIC VIDEO CLAIMS": "views",
    "RESSO": "streams",
    "SOUNDCLOUD": "streams",
    "TIKTOK": "videos",
    "IHEART RADIO": "streams",
    "DEEZER": "streams",
    "SNAPCHAT": "videos",
    "BOOMPLAY": "streams",
    "ANGHAMI": "streams",
    "TIDAL": "streams",
    "SPOTIFY": "streams",
    "WYNK": "streams",
    "YOUTUBE SHORTS": "views",
    "RHAPSODY/NAPSTER": "streams",
    "CLARO MÃƒÂšSICA": "streams",
    "ALIGENIE": "streams",
    "7 DIGITAL": "streams",
    "MONKINGME": "streams",
    "UNITED MEDIA AGENCY (UMA)": "streams",
    "NETEASE CLOUD MUSIC": "streams",
    "ITUNES": "downloads",
    "IPRS": "others",
    "IHEART": "streams",
    "PRS": "others",
    "MCPS": "others",
}

codes_validations = {
    "name": "codes",
    "required_columns": ["code", "type"],
    "db_mapping": {},
    "not_null_fields": ["code", "type"],
    "field_formats": {},
    "validation_text": [
        '<p style="text-align: left"><b>File format</b>: .xlsx<br>'
        "<b>Required columns</b>: code,type<br>",
        "<b>Non-Empty columns</b>: code,type<br><br>",
        "<b>Uploaded UPC/ISRC codes must not be present in the database.</b></p>",
    ],
}

payments_validations = {
    "name": "payments",
    "required_columns": [
        "username",
        "date_of_payment",
        "source_account",
        "sent_to_name",
        "sent_to_account_number",
        "sent_to_ifsc_code",
        "transfer_id",
        "amount_paid",
        "tds_percentage",
        "tds",
    ],
    "not_null_fields": [
        "username",
        "date_of_payment",
        "source_account",
        "sent_to_name",
        "sent_to_account_number",
        "sent_to_ifsc_code",
        "transfer_id",
        "amount_paid",
        "tds_percentage",
        "tds",
    ],
    "field_formats": {},
    "validation_text": [
        '<p style="text-align: left"><b>File format</b>: .xlsx<br>'
        "<b>Required columns</b>: username, date_of_payment, source_account, sent_to_name, sent_to_account_number, sent_to_ifsc_code, transfer_id, amount_paid, tds_percentage, tds<br>",
        "<b>Non-Empty columns</b>: username, date_of_payment, source_account, sent_to_name, sent_to_account_number, sent_to_ifsc_code, transfer_id, amount_paid, tds_percentage, tds",
    ],
}

roaylties_to_distribute_artists_mapping = {
    "Primary Artist": "primary",
    "Performer": "performer",
    "Producer": "producer",
    "Remixer": "remixer",
    "Composer": "composer",
    "Lyricist": "lyricist",
    "Featuring": "featuring",
    "Featured Artist": "featuring",  # Fix: Added mapping for "Featured Artist" role
    "Featuring Artist": "featuring",  # Fix: Added mapping for "Featuring Artist" role (if used in UI)
    "with": "with",
    "Conductor": "conductor",
    "Arranger": "arranger",
    "Orchestra": "orchestra",
    "Actor": "actor",
    "Remixer":"remixer",
    "Conductor":"conductor",
    "Orchestra":"orchestra",
    "Actor":"actor",
    "Accordion":"accordion",
    "Background Vocals":"background_vocals",
    "Banjo":"banjo",
    "Bass Guitar":"bass_guitar",
    "Bassoon":"bassoon",
    "Bells":"bells",
    "Cello":"cello",
    "Choir":"choir",
    "Clarinet":"clarinet",  # Fix: Fixed typo from "Clarient"
    "Clarient":"clarinet",  # Keep for backward compatibility (typo fix)
    "Drums":"drums",
    "Ensemble":"ensemble",
    "Fiddle":"fiddle",
    "Flute":"flute",
    "Guitar":"guitar",
    "Harmonica":"harmonica",
    "Harp":"harp",
    "Horn":"horn",
    "Keyboards":"keyboards",
    "Lute":"lute",
    "Metallophone":"metallophone",
    "Oboe":"oboe",
    "Organ":"organ",
    "Percussion":"percussion",
    "Piano":"piano",
    "Programming":"programming",
    "Rap":"rap",
    "Recorder":"recorder",
    "Saxophone":"saxophone",
    "Synthesizer":"synthesizer",
    "Tambourine":"tambourine",
    "Trombone":"trombone",
    "Trumpet":"trumpet",
    "Viola":"viola",
    "Viola De Gamba":"viola_de_gamba",
    "Viola de Gamba":"viola_de_gamba",  # Fix: Added mapping for "Viola de Gamba" (lowercase 'd')
    "Violin":"violin",
    "Vocals":"vocals",
    "Whistle":"whistle",
    "Xylophone":"xylophone",
    # Fix: Added missing role mappings to prevent KeyError during distribution
    "Adapter":"adapter",
    "Assistant Engineer":"assistant_engineer",
    "Co-Producer":"co_producer",
    "Graphic Design":"graphic_design",
    "Mastering Engineer":"mastering_engineer",
    "Mixing Engineer":"mixing_engineer",
    "Other Performer":"other_performer",
    "Publisher":"publisher",
    "Recording Engineer":"recording_engineer",
}

royalties_to_distribute_language_mapping = {
    "Afrikaans": "af",
    "Arabic": "ar",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bulgarian": "bg",
    "Cambodian": "km",
    "Cantonese": "yue",
    "Catalan": "ca",
    "Chinese": "zh",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Estonian": "et",
    "Finnish": "fi",
    "French": "fr",
    "German": "de",
    "Greek": "el",
    "Haitian": "ht",
    "Haryanvi": "bgc",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Indonesian": "id",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Kazakh": "kk",
    "Korean": "ko",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lithuanian": "lt",
    "Luganda": "lg",
    "Malay": "ms",
    "Mongolian": "mn",
    "Nepali": "ne",
    "Norwegian": "no",
    "Oriya": "or",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Romanian": "ro",
    "Russian": "ru",
    "Sanskrit": "sa",
    "Slovak": "sk",
    "Slovene": "sl",
    "Spanish": "es",
    "Swedish": "sv",
    "Tagalog": "tl",
    "Tamazight": "zgh",
    "Tamil": "ta",
    "Telugu": "te",
    "Thai": "th",
    "Turkish": "tr",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Vietnamese": "vi",
    "Zulu": "zu"
}
