# Generated by Django 5.2.2 on 2025-06-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_models", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_models.cduser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="cduser",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_models.cduser",
                verbose_name="Parent",
            ),
        ),
        migrations.AlterField(
            model_name="dueamount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="due_amounts",
                to="app_models.cduser",
                unique=True,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app_models.cduser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="ratio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratios",
                to="app_models.cduser",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_models.cduser",
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="app_models.cduser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="sharing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="app_models.cduser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_models.cduser",
                verbose_name="Created by",
            ),
        ),
    ]
