"""
Map release/track language names (from models.LANGUAGES) to ISO 639-1/639-2 codes for DDEX.
DDEX uses LanguageAndScriptCode like 'en', 'pa', 'hi' (2-letter preferred).
"""

# Map full language name -> ISO 639-1 (2-letter) or 639-2 (3-letter) for DDEX
# Default to 'en' if not found. Add more as needed.
LANGUAGE_TO_ISO = {
    "Afrikaans": "af",
    "Amharic": "am",
    "Arabic": "ar",
    "Arabic - Egyptian": "ar",
    "Arabic - Moroccan": "ar",
    "Armenian": "hy",
    "Assamese": "as",
    "Azerbaijani": "az",
    "Basque": "eu",
    "Belarusian": "be",
    "Bengali": "bn",
    "Bhojpuri": "bho",  # 639-3, use as-is or "hi"
    "Bosnian": "bs",
    "Bulgarian": "bg",
    "Cambodian": "km",
    "Catalan": "ca",
    "Chechen": "ce",
    "Chinese": "zh",
    "Chinese - Cantonese": "yue",
    "Chinese - Hakka": "hak",
    "Chinese - Mandarin": "zh",
    "Croatian": "hr",
    "Czech": "cs",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Estonian": "et",
    "Filipino": "fil",
    "Finnish": "fi",
    "French": "fr",
    "Galician": "gl",
    "Georgian": "ka",
    "German": "de",
    "Greek": "el",
    "Gujarati": "gu",
    "Haitian": "ht",
    "Haitian Creole": "ht",
    "Haryanvi": "hi",
    "Hawaiian": "haw",
    "Hebrew": "he",
    "Hindi": "hi",
    "Hungarian": "hu",
    "Icelandic": "is",
    "Igbo": "ig",
    "Indonesian": "id",
    "Irish": "ga",
    "Italian": "it",
    "Japanese": "ja",
    "Kannada": "kn",
    "Kazakh": "kk",
    "Konkani": "kok",
    "Korean": "ko",
    "Kurdish": "ku",
    "Lao": "lo",
    "Latin": "la",
    "Latvian": "lv",
    "Lingala": "ln",
    "Lithuanian": "lt",
    "Luganda": "lg",
    "Macedonian": "mk",
    "Malay": "ms",
    "Malayalam": "ml",
    "Maori": "mi",
    "Marathi": "mr",
    "Mongolian": "mn",
    "Nepali": "ne",
    "Norwegian": "no",
    "Oriya": "or",
    "Persian": "fa",
    "Polish": "pl",
    "Portuguese": "pt",
    "Punjabi": "pa",
    "Rajasthani": "hi",
    "Romanian": "ro",
    "Russian": "ru",
    "Samoan": "sm",
    "Sanskrit": "sa",
    "Sepedi": "nso",
    "Serbian": "sr",
    "Shona": "sn",
    "Slovak": "sk",
    "Slovene": "sl",
    "Sotho": "st",
    "Spanish": "es",
    "Swahili": "sw",
    "Swedish": "sv",
    "Tagalog": "tl",
    "Tahitian": "ty",
    "Tamazight": "tzm",
    "Tamil": "ta",
    "Telugu": "te",
    "Thai": "th",
    "Tsonga": "ts",
    "Tswana": "tn",
    "Turkish": "tr",
    "Twi": "tw",
    "Ukrainian": "uk",
    "Urdu": "ur",
    "Venda": "ve",
    "Vietnamese": "vi",
    "Xhosa": "xh",
    "Zulu": "zu",
}


def language_to_iso(language_name: str) -> str:
    """Return ISO 639-1/639-2 code for DDEX. Default 'en' if unknown."""
    if not language_name:
        return "en"
    return LANGUAGE_TO_ISO.get(language_name.strip(), "en")
