# Generated by Django 5.2.2 on 2025-06-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                (
                    "isrc",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISRC",
                    ),
                ),
                ("release", models.CharField(max_length=2000, verbose_name="Release")),
                (
                    "display_artist",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Display Artist",
                    ),
                ),
                (
                    "release_launch",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Release Launch"
                    ),
                ),
                ("user", models.CharField(max_length=200, verbose_name="User")),
                (
                    "label_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Label Name"
                    ),
                ),
                (
                    "primary_genre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Primary Genre",
                    ),
                ),
                (
                    "secondary_genre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Secondary Genre",
                    ),
                ),
                (
                    "track_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Track Number"
                    ),
                ),
                ("track", models.CharField(max_length=2000, verbose_name="Track")),
                (
                    "track_display_artist",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Track Display Artist",
                    ),
                ),
                (
                    "track_primary_genre",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Track Primary Genre",
                    ),
                ),
                (
                    "upc",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="UPC"
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadata",
                "verbose_name_plural": "Metadata",
                "indexes": [
                    models.Index(fields=["isrc"], name="ISRC_metadata"),
                    models.Index(fields=["user"], name="users_metadata"),
                ],
            },
        ),
    ]
