# Generated by Django 5.2.2 on 2025-06-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0002_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="artist_id",
            field=models.IntegerField(default=0, unique=True, verbose_name="Artist ID"),
            preserve_default=False,
        ),
    ]
