# Generated by Django 5.2.2 on 2025-06-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0003_artist_artist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artist_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Artist ID"),
        ),
    ]
