# Generated by Django 4.2.21 on 2025-06-18 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("releases", "0004_alter_artist_artist_id"),
    ]


    operations = [
        # Drop the table if it already exists
        migrations.RunSQL(
            "DROP TABLE IF EXISTS releases_splitreleaseroyalty;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="SplitReleaseRoyalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=255, verbose_name="Recipient Name"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="Recipient Email"),
                ),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("Primary Artist", "Primary Artist"),
                            ("Performer", "Performer"),
                            ("Producer", "Producer"),
                            ("Remixer", "Remixer"),
                            ("Composer", "Composer"),
                            ("Lyricist", "Lyricist"),
                            ("Featuring", "Featuring"),
                            ("with", "with"),
                            ("Conductor", "Conductor"),
                            ("Arranger", "Arranger"),
                            ("Orchestra", "Orchestra"),
                            ("Actor", "Actor"),
                            ("Xylophone", "Xylophone"),
                            ("Whistle", "Whistle"),
                            ("Vocals", "Vocals"),
                            ("Violin", "Violin"),
                            ("Viola De Gamba", "Viola De Gamba"),
                            ("Viola", "Viola"),
                            ("Trumpet", "Trumpet"),
                            ("Trombone", "Trombone"),
                            ("Tambourine", "Tambourine"),
                            ("Synthesizer", "Synthesizer"),
                            ("Saxophone", "Saxophone"),
                            ("Recorder", "Recorder"),
                            ("Rap", "Rap"),
                            ("Programming", "Programming"),
                            ("Piano", "Piano"),
                            ("Percussion", "Percussion"),
                            ("Organ", "Organ"),
                            ("Oboe", "Oboe"),
                            ("Metallophone", "Metallophone"),
                            ("Lute", "Lute"),
                            ("Keyboards", "Keyboards"),
                            ("Horn", "Horn"),
                            ("Harp", "Harp"),
                            ("Harmonica", "Harmonica"),
                            ("Guitar", "Guitar"),
                            ("Flute", "Flute"),
                            ("Fiddle", "Fiddle"),
                            ("Ensemble", "Ensemble"),
                            ("Drums", "Drums"),
                            ("Clarinet", "Clarinet"),
                            ("Choir", "Choir"),
                            ("Cello", "Cello"),
                            ("Bells", "Bells"),
                        ],
                        max_length=255,
                        verbose_name="Role",
                    ),
                ),
                ("recipient_percentage", models.FloatField(verbose_name="Percentage")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "release_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_release_royalties",
                        to="releases.release",
                    ),
                ),
                (
                    "track_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_release_royalties",
                        to="releases.track",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_release_royalties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Split Release Royalty",
                "verbose_name_plural": "Split Release Royalties",
            },
        ),
        migrations.AddConstraint(
            model_name="splitreleaseroyalty",
            constraint=models.UniqueConstraint(
                fields=("user_id", "recipient_email", "release_id", "track_id"),
                name="unique_user_release_track",
            ),
        ),
    ]
