# Generated by Django 5.2.2 on 2025-06-20 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0005_splitreleaseroyalty_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(fields=["upc"], name="upc_metadata"),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(
                fields=["relation_key"], name="releases_re_relatio_ca6b3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(fields=["role"], name="releases_re_role_f4282a_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["title"], name="releases_re_title_cef450_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["upc"], name="releases_re_upc_30fe95_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["reference_number"], name="releases_re_referen_ae7a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(fields=["grid"], name="releases_re_grid_6b269f_idx"),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["language"], name="releases_re_languag_720adf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["created_by"], name="releases_re_created_59a0a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["updated_at"], name="releases_re_updated_ae4cf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["gross_total_INR"], name="releases_ro_gross_t_bb9af9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["net_total"], name="releases_ro_net_tot_c7acdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["net_total_INR"], name="releases_ro_net_tot_a0e083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["confirmed_date"], name="releases_ro_confirm_445277_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["user_id"], name="releases_sp_user_id_305ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["release_id"], name="releases_sp_release_1d34cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["track_id"], name="releases_sp_track_i_b5527e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["recipient_email"], name="releases_sp_recipie_378507_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["recipient_name"], name="releases_sp_recipie_79db49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["recipient_role"], name="releases_sp_recipie_b91cef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["created_at"], name="releases_sp_created_42914c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["updated_at"], name="releases_sp_updated_bffbff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["isrc"], name="releases_tr_isrc_542259_idx"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["primary_genre"], name="releases_tr_primary_6b0c9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["secondary_genre"], name="releases_tr_seconda_9958cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["language"], name="releases_tr_languag_2737e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["created_by"], name="releases_tr_created_703316_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["updated_at"], name="releases_tr_updated_aee27f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniquecode",
            index=models.Index(fields=["type"], name="releases_un_type_2839d6_idx"),
        ),
        migrations.AddIndex(
            model_name="uniquecode",
            index=models.Index(
                fields=["assigned"], name="releases_un_assigne_9a2b16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniquecode",
            index=models.Index(
                fields=["created_at"], name="releases_un_created_311bdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uniquecode",
            index=models.Index(
                fields=["updated_at"], name="releases_un_updated_7579db_idx"
            ),
        ),
    ]
