# Generated by Django 5.2.2 on 2025-06-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0007_remove_metadata_release_metadata_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["end_date"], name="releases_ro_end_dat_4aeeda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["start_date"], name="releases_ro_start_d_f00e08_idx"
            ),
        ),
    ]
