# Generated by Django 5.2.2 on 2025-07-27 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0008_royalties_releases_ro_end_dat_4aeeda_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["user"], name="releases_ar_user_id_32dcdd_idx"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="releases_ar_name_b506f6_idx"),
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["user"], name="releases_la_user_id_3d0c0c_idx"),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["release_launch"], name="releases_me_release_e1b6bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["label_name"], name="releases_me_label_n_d5be99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["primary_genre"], name="releases_me_primary_1bca12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["track_display_artist"], name="releases_me_track_d_3084ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["user", "isrc"], name="releases_me_user_effb1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["user", "primary_genre"], name="releases_me_user_44666e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(
                fields=["artist"], name="releases_re_artist__201ef4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(
                fields=["release"], name="releases_re_release_6cf814_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(fields=["track"], name="releases_re_track_i_1f98f7_idx"),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(
                fields=["track", "artist"], name="releases_re_track_i_051a3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="relatedartists",
            index=models.Index(
                fields=["release", "artist"], name="releases_re_release_bc14ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["published"], name="releases_re_publish_4f28ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["published_at"], name="releases_re_publish_35a24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["primary_genre"], name="releases_re_primary_978079_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["album_format"], name="releases_re_album_f_72384b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["digital_release_date"], name="releases_re_digital_68f12c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["created_by", "published"],
                name="releases_re_created_82ef18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="release",
            index=models.Index(
                fields=["label", "created_by"], name="releases_re_label_i_75b147_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["country"], name="releases_ro_country_36e20c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["currency"], name="releases_ro_currenc_f8f02f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(fields=["type"], name="releases_ro_type_4a5bd9_idx"),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["isrc", "net_total_INR"], name="releases_ro_isrc_261ce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="royalties",
            index=models.Index(
                fields=["isrc", "net_total_INR", "confirmed_date"],
                name="releases_ro_isrc_89d035_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["recipient_percentage"], name="releases_sp_recipie_352649_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["user_id", "track_id"], name="releases_sp_user_id_8a1346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="splitreleaseroyalty",
            index=models.Index(
                fields=["user_id", "release_id"], name="releases_sp_user_id_234e46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["release"], name="releases_tr_release_8db281_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["release", "created_by"], name="releases_tr_release_cd27b9_idx"
            ),
        ),
    ]
