# Generated by Django - add submitted_for_approval_at for Pending for Approval sorting

from django.db import migrations, models


def backfill_submitted_at(apps, schema_editor):
    """Set submitted_for_approval_at = updated_at for existing pending releases."""
    Release = apps.get_model("releases", "Release")
    Release.objects.filter(
        approval_status__iexact="pending_approval",
        submitted_for_approval_at__isnull=True,
    ).update(submitted_for_approval_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("releases", "0011_add_sonosuite_operation_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="submitted_for_approval_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the release was submitted for distribution approval.",
                null=True,
                verbose_name="Submitted for approval at",
            ),
        ),
        migrations.RunPython(backfill_submitted_at, migrations.RunPython.noop),
    ]
