# Generated by Django 4.2.27 on 2026-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0015_track_audio_wav_mp3_flac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedartists',
            name='role',
            field=models.CharField(choices=[('Accordion', 'Accordion'), ('Actor', 'Actor'), ('Adapter', 'Adapter'), ('Assistant Engineer', 'Assistant Engineer'), ('Background Vocals', 'Background Vocals'), ('Banjo', 'Banjo'), ('Bass Guitar', 'Bass Guitar'), ('Bassoon', 'Bassoon'), ('Bells', 'Bells'), ('Cello', 'Cello'), ('Choir', 'Choir'), ('Clarinet', 'Clarinet'), ('Co-Producer', 'Co-Producer'), ('Composer', 'Composer'), ('Conductor', 'Conductor'), ('Drums', 'Drums'), ('Ensemble', 'Ensemble'), ('Featured Artist', 'Featured Artist'), ('Fiddle', 'Fiddle'), ('Flute', 'Flute'), ('Graphic Design', 'Graphic Design'), ('Guitar', 'Guitar'), ('Harmonica', 'Harmonica'), ('Harp', 'Harp'), ('Horn', 'Horn'), ('Keyboards', 'Keyboards'), ('Lute', 'Lute'), ('Lyricist', 'Lyricist'), ('Mastering Engineer', 'Mastering Engineer'), ('Metallophone', 'Metallophone'), ('Mixing Engineer', 'Mixing Engineer'), ('Oboe', 'Oboe'), ('Orchestra', 'Orchestra'), ('Organ', 'Organ'), ('Other Performer', 'Other Performer'), ('Percussion', 'Percussion'), ('Performer', 'Performer'), ('Piano', 'Piano'), ('Primary Artist', 'Primary Artist'), ('Producer', 'Producer'), ('Programming', 'Programming'), ('Rap', 'Rap'), ('Recording Engineer', 'Recording Engineer'), ('Recorder', 'Recorder'), ('Remixer', 'Remixer'), ('Saxophone', 'Saxophone'), ('Synthesizer', 'Synthesizer'), ('Tambourine', 'Tambourine'), ('Trombone', 'Trombone'), ('Trumpet', 'Trumpet'), ('Viola', 'Viola'), ('Viola de Gamba', 'Viola de Gamba'), ('Violin', 'Violin'), ('Vocals', 'Vocals'), ('Whistle', 'Whistle'), ('with', 'with'), ('Xylophone', 'Xylophone')], max_length=250, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='splitreleaseroyalty',
            name='recipient_role',
            field=models.CharField(choices=[('Accordion', 'Accordion'), ('Actor', 'Actor'), ('Adapter', 'Adapter'), ('Assistant Engineer', 'Assistant Engineer'), ('Background Vocals', 'Background Vocals'), ('Banjo', 'Banjo'), ('Bass Guitar', 'Bass Guitar'), ('Bassoon', 'Bassoon'), ('Bells', 'Bells'), ('Cello', 'Cello'), ('Choir', 'Choir'), ('Clarinet', 'Clarinet'), ('Co-Producer', 'Co-Producer'), ('Composer', 'Composer'), ('Conductor', 'Conductor'), ('Drums', 'Drums'), ('Ensemble', 'Ensemble'), ('Featured Artist', 'Featured Artist'), ('Fiddle', 'Fiddle'), ('Flute', 'Flute'), ('Graphic Design', 'Graphic Design'), ('Guitar', 'Guitar'), ('Harmonica', 'Harmonica'), ('Harp', 'Harp'), ('Horn', 'Horn'), ('Keyboards', 'Keyboards'), ('Lute', 'Lute'), ('Lyricist', 'Lyricist'), ('Mastering Engineer', 'Mastering Engineer'), ('Metallophone', 'Metallophone'), ('Mixing Engineer', 'Mixing Engineer'), ('Oboe', 'Oboe'), ('Orchestra', 'Orchestra'), ('Organ', 'Organ'), ('Other Performer', 'Other Performer'), ('Percussion', 'Percussion'), ('Performer', 'Performer'), ('Piano', 'Piano'), ('Primary Artist', 'Primary Artist'), ('Producer', 'Producer'), ('Programming', 'Programming'), ('Rap', 'Rap'), ('Recording Engineer', 'Recording Engineer'), ('Recorder', 'Recorder'), ('Remixer', 'Remixer'), ('Saxophone', 'Saxophone'), ('Synthesizer', 'Synthesizer'), ('Tambourine', 'Tambourine'), ('Trombone', 'Trombone'), ('Trumpet', 'Trumpet'), ('Viola', 'Viola'), ('Viola de Gamba', 'Viola de Gamba'), ('Violin', 'Violin'), ('Vocals', 'Vocals'), ('Whistle', 'Whistle'), ('with', 'with'), ('Xylophone', 'Xylophone')], max_length=255, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_flac_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Audio FLAC'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_mp3_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Audio MP3'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_track_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Audio Track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_wav_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Audio WAV'),
        ),
    ]
