# Generated by Django 4.2.27 on 2026-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0018_release_apple_music_preorder_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='apple_music_preorder_start_date',
            field=models.DateField(blank=True, help_text='If set, metadata.xml includes preorder_sales_start_date on each product (Merlin preorder checklist). Must be before Digital release date (street/sale date) and typically in the future when you deliver.', null=True, verbose_name='Apple Music pre-order sales start date'),
        ),
    ]
