# Generated by Django 4.2.27 on 2026-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0021_mysql_default_apple_music_commercial_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='apple_music_instant_grat',
            field=models.BooleanField(default=False, help_text='During an Apple Music pre-order, mark tracks that are instant gratification. Deliveries emit <preorder_type>instant-gratification</preorder_type> on those tracks and <preorder_type>standard</preorder_type> on others (track-level, not inside <product>). At most half the tracks may be IG.', verbose_name='Apple Music instant gratification (pre-order)'),
        ),
    ]
