# Generated by Django 4.2.27 on 2026-03-20 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('releases', '0023_mysql_default_apple_music_instant_grat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('distribute', 'Distribute to stores'), ('takedown', 'Takedown from stores')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('store_results', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, default='')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_jobs', to='releases.release')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribution Job',
                'verbose_name_plural': 'Distribution Jobs',
                'indexes': [models.Index(fields=['release', 'requested_at'], name='releases_di_release_8ec31d_idx'), models.Index(fields=['status', 'requested_at'], name='releases_di_status_9ac722_idx'), models.Index(fields=['action', 'requested_at'], name='releases_di_action_64a7b6_idx')],
            },
        ),
    ]
